(cl:defpackage corrosion_detector-srv
  (:use )
  (:export
   "CAMERASELECTOR"
   "<CAMERASELECTOR-REQUEST>"
   "CAMERASELECTOR-REQUEST"
   "<CAMERASELECTOR-RESPONSE>"
   "CAMERASELECTOR-RESPONSE"
   "TRIGGER"
   "<TRIGGER-REQUEST>"
   "TRIGGER-REQUEST"
   "<TRIGGER-RESPONSE>"
   "TRIGGER-RESPONSE"
  ))

