// Generated by gencpp from file corrosion_detector/AxisPoints.msg
// DO NOT EDIT!


#ifndef CORROSION_DETECTOR_MESSAGE_AXISPOINTS_H
#define CORROSION_DETECTOR_MESSAGE_AXISPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace corrosion_detector
{
template <class ContainerAllocator>
struct AxisPoints_
{
  typedef AxisPoints_<ContainerAllocator> Type;

  AxisPoints_()
    : header()
    , major_axis_p1()
    , major_axis_p2()
    , minor_axis_p1()
    , minor_axis_p2()
    , orientation(0.0)
    , major_axis_len(0.0)
    , minor_axis_len(0.0)  {
    }
  AxisPoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , major_axis_p1(_alloc)
    , major_axis_p2(_alloc)
    , minor_axis_p1(_alloc)
    , minor_axis_p2(_alloc)
    , orientation(0.0)
    , major_axis_len(0.0)
    , minor_axis_len(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _major_axis_p1_type;
  _major_axis_p1_type major_axis_p1;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _major_axis_p2_type;
  _major_axis_p2_type major_axis_p2;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _minor_axis_p1_type;
  _minor_axis_p1_type minor_axis_p1;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _minor_axis_p2_type;
  _minor_axis_p2_type minor_axis_p2;

   typedef double _orientation_type;
  _orientation_type orientation;

   typedef double _major_axis_len_type;
  _major_axis_len_type major_axis_len;

   typedef double _minor_axis_len_type;
  _minor_axis_len_type minor_axis_len;





  typedef boost::shared_ptr< ::corrosion_detector::AxisPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::corrosion_detector::AxisPoints_<ContainerAllocator> const> ConstPtr;

}; // struct AxisPoints_

typedef ::corrosion_detector::AxisPoints_<std::allocator<void> > AxisPoints;

typedef boost::shared_ptr< ::corrosion_detector::AxisPoints > AxisPointsPtr;
typedef boost::shared_ptr< ::corrosion_detector::AxisPoints const> AxisPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::corrosion_detector::AxisPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::corrosion_detector::AxisPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::corrosion_detector::AxisPoints_<ContainerAllocator1> & lhs, const ::corrosion_detector::AxisPoints_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.major_axis_p1 == rhs.major_axis_p1 &&
    lhs.major_axis_p2 == rhs.major_axis_p2 &&
    lhs.minor_axis_p1 == rhs.minor_axis_p1 &&
    lhs.minor_axis_p2 == rhs.minor_axis_p2 &&
    lhs.orientation == rhs.orientation &&
    lhs.major_axis_len == rhs.major_axis_len &&
    lhs.minor_axis_len == rhs.minor_axis_len;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::corrosion_detector::AxisPoints_<ContainerAllocator1> & lhs, const ::corrosion_detector::AxisPoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace corrosion_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::AxisPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::AxisPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::AxisPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::AxisPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::AxisPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::AxisPoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::corrosion_detector::AxisPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c40b075900f16fe11733d8a1bb7afb1b";
  }

  static const char* value(const ::corrosion_detector::AxisPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc40b075900f16fe1ULL;
  static const uint64_t static_value2 = 0x1733d8a1bb7afb1bULL;
};

template<class ContainerAllocator>
struct DataType< ::corrosion_detector::AxisPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "corrosion_detector/AxisPoints";
  }

  static const char* value(const ::corrosion_detector::AxisPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::corrosion_detector::AxisPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# List of 2D points\n"
"geometry_msgs/Point major_axis_p1\n"
"geometry_msgs/Point major_axis_p2\n"
"geometry_msgs/Point minor_axis_p1\n"
"geometry_msgs/Point minor_axis_p2\n"
"\n"
"# Orientation of the axis (yaw in radians)\n"
"float64 orientation\n"
"\n"
"# Axis lenghts\n"
"float64 major_axis_len\n"
"float64 minor_axis_len\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::corrosion_detector::AxisPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::corrosion_detector::AxisPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.major_axis_p1);
      stream.next(m.major_axis_p2);
      stream.next(m.minor_axis_p1);
      stream.next(m.minor_axis_p2);
      stream.next(m.orientation);
      stream.next(m.major_axis_len);
      stream.next(m.minor_axis_len);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AxisPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::corrosion_detector::AxisPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::corrosion_detector::AxisPoints_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "major_axis_p1: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.major_axis_p1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "major_axis_p2: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.major_axis_p2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "minor_axis_p1: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.minor_axis_p1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "minor_axis_p2: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.minor_axis_p2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "orientation: ";
    Printer<double>::stream(s, indent + "  ", v.orientation);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "major_axis_len: ";
    Printer<double>::stream(s, indent + "  ", v.major_axis_len);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "minor_axis_len: ";
    Printer<double>::stream(s, indent + "  ", v.minor_axis_len);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORROSION_DETECTOR_MESSAGE_AXISPOINTS_H
