// Generated by gencpp from file corrosion_detector/BoundingBoxArray.msg
// DO NOT EDIT!


#ifndef CORROSION_DETECTOR_MESSAGE_BOUNDINGBOXARRAY_H
#define CORROSION_DETECTOR_MESSAGE_BOUNDINGBOXARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <corrosion_detector/BoundingBox.h>

namespace corrosion_detector
{
template <class ContainerAllocator>
struct BoundingBoxArray_
{
  typedef BoundingBoxArray_<ContainerAllocator> Type;

  BoundingBoxArray_()
    : header()
    , boxes()  {
    }
  BoundingBoxArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , boxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::corrosion_detector::BoundingBox_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::corrosion_detector::BoundingBox_<ContainerAllocator> >> _boxes_type;
  _boxes_type boxes;





  typedef boost::shared_ptr< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBoxArray_

typedef ::corrosion_detector::BoundingBoxArray_<std::allocator<void> > BoundingBoxArray;

typedef boost::shared_ptr< ::corrosion_detector::BoundingBoxArray > BoundingBoxArrayPtr;
typedef boost::shared_ptr< ::corrosion_detector::BoundingBoxArray const> BoundingBoxArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::corrosion_detector::BoundingBoxArray_<ContainerAllocator1> & lhs, const ::corrosion_detector::BoundingBoxArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.boxes == rhs.boxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::corrosion_detector::BoundingBoxArray_<ContainerAllocator1> & lhs, const ::corrosion_detector::BoundingBoxArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace corrosion_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4acd9e8a28a9feaebd1bd8961261358";
  }

  static const char* value(const ::corrosion_detector::BoundingBoxArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4acd9e8a28a9feaULL;
  static const uint64_t static_value2 = 0xebd1bd8961261358ULL;
};

template<class ContainerAllocator>
struct DataType< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "corrosion_detector/BoundingBoxArray";
  }

  static const char* value(const ::corrosion_detector::BoundingBoxArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header        # Importante para el timestamp\n"
"BoundingBox[] boxes  # La lista de cajas (puede haber 0, 1 o 20)\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: corrosion_detector/BoundingBox\n"
"string class_id      # \"0\", \"person\", etc.\n"
"float64 score        # Probabilidad (0.0 a 1.0)\n"
"\n"
"# Coordenadas NORMALIZADAS (0.0 a 1.0)\n"
"# Es lo estándar en YOLO y facilita la vida al siguiente nodo\n"
"float64 x            # Centro X\n"
"float64 y            # Centro Y\n"
"float64 w            # Ancho\n"
"float64 h            # Alto\n"
"\n"
"# Coordenades normalitzades del Punt de corrosió\n"
"float64 corr_x\n"
"float64 corr_y\n"
"float64 std_x\n"
"float64 std_y\n"
"float64 area\n"
"int16 width\n"
"int16 height\n"
;
  }

  static const char* value(const ::corrosion_detector::BoundingBoxArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.boxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBoxArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::corrosion_detector::BoundingBoxArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::corrosion_detector::BoundingBoxArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "boxes: ";
    if (v.boxes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.boxes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::corrosion_detector::BoundingBox_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.boxes[i]);
    }
    if (v.boxes.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORROSION_DETECTOR_MESSAGE_BOUNDINGBOXARRAY_H
