// Generated by gencpp from file corrosion_detector/BoundingBox.msg
// DO NOT EDIT!


#ifndef CORROSION_DETECTOR_MESSAGE_BOUNDINGBOX_H
#define CORROSION_DETECTOR_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace corrosion_detector
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : class_id()
    , score(0.0)
    , x(0.0)
    , y(0.0)
    , w(0.0)
    , h(0.0)
    , corr_x(0.0)
    , corr_y(0.0)
    , std_x(0.0)
    , std_y(0.0)
    , area(0.0)
    , width(0)
    , height(0)  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : class_id(_alloc)
    , score(0.0)
    , x(0.0)
    , y(0.0)
    , w(0.0)
    , h(0.0)
    , corr_x(0.0)
    , corr_y(0.0)
    , std_x(0.0)
    , std_y(0.0)
    , area(0.0)
    , width(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_id_type;
  _class_id_type class_id;

   typedef double _score_type;
  _score_type score;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _w_type;
  _w_type w;

   typedef double _h_type;
  _h_type h;

   typedef double _corr_x_type;
  _corr_x_type corr_x;

   typedef double _corr_y_type;
  _corr_y_type corr_y;

   typedef double _std_x_type;
  _std_x_type std_x;

   typedef double _std_y_type;
  _std_y_type std_y;

   typedef double _area_type;
  _area_type area;

   typedef int16_t _width_type;
  _width_type width;

   typedef int16_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::corrosion_detector::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::corrosion_detector::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::corrosion_detector::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::corrosion_detector::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::corrosion_detector::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::corrosion_detector::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::corrosion_detector::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::corrosion_detector::BoundingBox_<ContainerAllocator1> & lhs, const ::corrosion_detector::BoundingBox_<ContainerAllocator2> & rhs)
{
  return lhs.class_id == rhs.class_id &&
    lhs.score == rhs.score &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.w == rhs.w &&
    lhs.h == rhs.h &&
    lhs.corr_x == rhs.corr_x &&
    lhs.corr_y == rhs.corr_y &&
    lhs.std_x == rhs.std_x &&
    lhs.std_y == rhs.std_y &&
    lhs.area == rhs.area &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::corrosion_detector::BoundingBox_<ContainerAllocator1> & lhs, const ::corrosion_detector::BoundingBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace corrosion_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::corrosion_detector::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce1d7034235b18cb9d0c6436906febbb";
  }

  static const char* value(const ::corrosion_detector::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce1d7034235b18cbULL;
  static const uint64_t static_value2 = 0x9d0c6436906febbbULL;
};

template<class ContainerAllocator>
struct DataType< ::corrosion_detector::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "corrosion_detector/BoundingBox";
  }

  static const char* value(const ::corrosion_detector::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::corrosion_detector::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string class_id      # \"0\", \"person\", etc.\n"
"float64 score        # Probabilidad (0.0 a 1.0)\n"
"\n"
"# Coordenadas NORMALIZADAS (0.0 a 1.0)\n"
"# Es lo estándar en YOLO y facilita la vida al siguiente nodo\n"
"float64 x            # Centro X\n"
"float64 y            # Centro Y\n"
"float64 w            # Ancho\n"
"float64 h            # Alto\n"
"\n"
"# Coordenades normalitzades del Punt de corrosió\n"
"float64 corr_x\n"
"float64 corr_y\n"
"float64 std_x\n"
"float64 std_y\n"
"float64 area\n"
"int16 width\n"
"int16 height\n"
;
  }

  static const char* value(const ::corrosion_detector::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::corrosion_detector::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_id);
      stream.next(m.score);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
      stream.next(m.corr_x);
      stream.next(m.corr_y);
      stream.next(m.std_x);
      stream.next(m.std_y);
      stream.next(m.area);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::corrosion_detector::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::corrosion_detector::BoundingBox_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "class_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "score: ";
    Printer<double>::stream(s, indent + "  ", v.score);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "h: ";
    Printer<double>::stream(s, indent + "  ", v.h);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "corr_x: ";
    Printer<double>::stream(s, indent + "  ", v.corr_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "corr_y: ";
    Printer<double>::stream(s, indent + "  ", v.corr_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "std_x: ";
    Printer<double>::stream(s, indent + "  ", v.std_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "std_y: ";
    Printer<double>::stream(s, indent + "  ", v.std_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "area: ";
    Printer<double>::stream(s, indent + "  ", v.area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<int16_t>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<int16_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORROSION_DETECTOR_MESSAGE_BOUNDINGBOX_H
