// Generated by gencpp from file corrosion_detector/CameraSelector.msg
// DO NOT EDIT!


#ifndef CORROSION_DETECTOR_MESSAGE_CAMERASELECTOR_H
#define CORROSION_DETECTOR_MESSAGE_CAMERASELECTOR_H

#include <ros/service_traits.h>


#include <corrosion_detector/CameraSelectorRequest.h>
#include <corrosion_detector/CameraSelectorResponse.h>


namespace corrosion_detector
{

struct CameraSelector
{

typedef CameraSelectorRequest Request;
typedef CameraSelectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraSelector
} // namespace corrosion_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::corrosion_detector::CameraSelector > {
  static const char* value()
  {
    return "1dd2bbcf551a47af8b1e8f3d1a8936e5";
  }

  static const char* value(const ::corrosion_detector::CameraSelector&) { return value(); }
};

template<>
struct DataType< ::corrosion_detector::CameraSelector > {
  static const char* value()
  {
    return "corrosion_detector/CameraSelector";
  }

  static const char* value(const ::corrosion_detector::CameraSelector&) { return value(); }
};


// service_traits::MD5Sum< ::corrosion_detector::CameraSelectorRequest> should match
// service_traits::MD5Sum< ::corrosion_detector::CameraSelector >
template<>
struct MD5Sum< ::corrosion_detector::CameraSelectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::corrosion_detector::CameraSelector >::value();
  }
  static const char* value(const ::corrosion_detector::CameraSelectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::corrosion_detector::CameraSelectorRequest> should match
// service_traits::DataType< ::corrosion_detector::CameraSelector >
template<>
struct DataType< ::corrosion_detector::CameraSelectorRequest>
{
  static const char* value()
  {
    return DataType< ::corrosion_detector::CameraSelector >::value();
  }
  static const char* value(const ::corrosion_detector::CameraSelectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::corrosion_detector::CameraSelectorResponse> should match
// service_traits::MD5Sum< ::corrosion_detector::CameraSelector >
template<>
struct MD5Sum< ::corrosion_detector::CameraSelectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::corrosion_detector::CameraSelector >::value();
  }
  static const char* value(const ::corrosion_detector::CameraSelectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::corrosion_detector::CameraSelectorResponse> should match
// service_traits::DataType< ::corrosion_detector::CameraSelector >
template<>
struct DataType< ::corrosion_detector::CameraSelectorResponse>
{
  static const char* value()
  {
    return DataType< ::corrosion_detector::CameraSelector >::value();
  }
  static const char* value(const ::corrosion_detector::CameraSelectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORROSION_DETECTOR_MESSAGE_CAMERASELECTOR_H
