// Generated by gencpp from file corrosion_detector/CoordinatesError.msg
// DO NOT EDIT!


#ifndef CORROSION_DETECTOR_MESSAGE_COORDINATESERROR_H
#define CORROSION_DETECTOR_MESSAGE_COORDINATESERROR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace corrosion_detector
{
template <class ContainerAllocator>
struct CoordinatesError_
{
  typedef CoordinatesError_<ContainerAllocator> Type;

  CoordinatesError_()
    : header()
    , x_err(0.0)
    , y_err(0.0)
    , z_err(0.0)
    , total_error(0.0)  {
    }
  CoordinatesError_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x_err(0.0)
    , y_err(0.0)
    , z_err(0.0)
    , total_error(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _x_err_type;
  _x_err_type x_err;

   typedef double _y_err_type;
  _y_err_type y_err;

   typedef double _z_err_type;
  _z_err_type z_err;

   typedef double _total_error_type;
  _total_error_type total_error;





  typedef boost::shared_ptr< ::corrosion_detector::CoordinatesError_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::corrosion_detector::CoordinatesError_<ContainerAllocator> const> ConstPtr;

}; // struct CoordinatesError_

typedef ::corrosion_detector::CoordinatesError_<std::allocator<void> > CoordinatesError;

typedef boost::shared_ptr< ::corrosion_detector::CoordinatesError > CoordinatesErrorPtr;
typedef boost::shared_ptr< ::corrosion_detector::CoordinatesError const> CoordinatesErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::corrosion_detector::CoordinatesError_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::corrosion_detector::CoordinatesError_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::corrosion_detector::CoordinatesError_<ContainerAllocator1> & lhs, const ::corrosion_detector::CoordinatesError_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x_err == rhs.x_err &&
    lhs.y_err == rhs.y_err &&
    lhs.z_err == rhs.z_err &&
    lhs.total_error == rhs.total_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::corrosion_detector::CoordinatesError_<ContainerAllocator1> & lhs, const ::corrosion_detector::CoordinatesError_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace corrosion_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::CoordinatesError_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::CoordinatesError_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::CoordinatesError_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::CoordinatesError_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::CoordinatesError_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::CoordinatesError_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::corrosion_detector::CoordinatesError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f51f162e146a2cd618e4c2bc2935431c";
  }

  static const char* value(const ::corrosion_detector::CoordinatesError_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf51f162e146a2cd6ULL;
  static const uint64_t static_value2 = 0x18e4c2bc2935431cULL;
};

template<class ContainerAllocator>
struct DataType< ::corrosion_detector::CoordinatesError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "corrosion_detector/CoordinatesError";
  }

  static const char* value(const ::corrosion_detector::CoordinatesError_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::corrosion_detector::CoordinatesError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# Coordenadas del error (posicion ground_truth - posicion calculada)\n"
"float64 x_err \n"
"float64 y_err\n"
"float64 z_err\n"
"\n"
"# Distancia euclídea entre los 2 puntos en 3 dimensiones\n"
"float64 total_error\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::corrosion_detector::CoordinatesError_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::corrosion_detector::CoordinatesError_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x_err);
      stream.next(m.y_err);
      stream.next(m.z_err);
      stream.next(m.total_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoordinatesError_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::corrosion_detector::CoordinatesError_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::corrosion_detector::CoordinatesError_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_err: ";
    Printer<double>::stream(s, indent + "  ", v.x_err);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_err: ";
    Printer<double>::stream(s, indent + "  ", v.y_err);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z_err: ";
    Printer<double>::stream(s, indent + "  ", v.z_err);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_error: ";
    Printer<double>::stream(s, indent + "  ", v.total_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORROSION_DETECTOR_MESSAGE_COORDINATESERROR_H
