// Generated by gencpp from file corrosion_detector/Detection3DArray.msg
// DO NOT EDIT!


#ifndef CORROSION_DETECTOR_MESSAGE_DETECTION3DARRAY_H
#define CORROSION_DETECTOR_MESSAGE_DETECTION3DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <corrosion_detector/Detection3D.h>

namespace corrosion_detector
{
template <class ContainerAllocator>
struct Detection3DArray_
{
  typedef Detection3DArray_<ContainerAllocator> Type;

  Detection3DArray_()
    : header()
    , detections()  {
    }
  Detection3DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::corrosion_detector::Detection3D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::corrosion_detector::Detection3D_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::corrosion_detector::Detection3DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::corrosion_detector::Detection3DArray_<ContainerAllocator> const> ConstPtr;

}; // struct Detection3DArray_

typedef ::corrosion_detector::Detection3DArray_<std::allocator<void> > Detection3DArray;

typedef boost::shared_ptr< ::corrosion_detector::Detection3DArray > Detection3DArrayPtr;
typedef boost::shared_ptr< ::corrosion_detector::Detection3DArray const> Detection3DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::corrosion_detector::Detection3DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::corrosion_detector::Detection3DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::corrosion_detector::Detection3DArray_<ContainerAllocator1> & lhs, const ::corrosion_detector::Detection3DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::corrosion_detector::Detection3DArray_<ContainerAllocator1> & lhs, const ::corrosion_detector::Detection3DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace corrosion_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::Detection3DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::Detection3DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::Detection3DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::Detection3DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::Detection3DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::Detection3DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::corrosion_detector::Detection3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6614de60092c15ffd08b1a8bb5742ea";
  }

  static const char* value(const ::corrosion_detector::Detection3DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6614de60092c15fULL;
  static const uint64_t static_value2 = 0xfd08b1a8bb5742eaULL;
};

template<class ContainerAllocator>
struct DataType< ::corrosion_detector::Detection3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "corrosion_detector/Detection3DArray";
  }

  static const char* value(const ::corrosion_detector::Detection3DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::corrosion_detector::Detection3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Detection3D[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: corrosion_detector/Detection3D\n"
"string class_id\n"
"float64 score\n"
"float64 x  # Metros\n"
"float64 y  # Metros\n"
"float64 z  # Metros\n"
"float64 width\n"
"float64 height\n"
"float64 area_px\n"
"float64 area_real\n"
"bool is_corrosion # Valor en bool per a poder distingir entre cas de corrosio i de xarxa\n"
;
  }

  static const char* value(const ::corrosion_detector::Detection3DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::corrosion_detector::Detection3DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection3DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::corrosion_detector::Detection3DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::corrosion_detector::Detection3DArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::corrosion_detector::Detection3D_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORROSION_DETECTOR_MESSAGE_DETECTION3DARRAY_H
