// Generated by gencpp from file corrosion_detector/NetStats.msg
// DO NOT EDIT!


#ifndef CORROSION_DETECTOR_MESSAGE_NETSTATS_H
#define CORROSION_DETECTOR_MESSAGE_NETSTATS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace corrosion_detector
{
template <class ContainerAllocator>
struct NetStats_
{
  typedef NetStats_<ContainerAllocator> Type;

  NetStats_()
    : header()
    , scale_m_per_px(0.0)
    , median_hole_area_px(0.0)
    , median_hole_area_m2(0.0)  {
    }
  NetStats_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , scale_m_per_px(0.0)
    , median_hole_area_px(0.0)
    , median_hole_area_m2(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _scale_m_per_px_type;
  _scale_m_per_px_type scale_m_per_px;

   typedef float _median_hole_area_px_type;
  _median_hole_area_px_type median_hole_area_px;

   typedef float _median_hole_area_m2_type;
  _median_hole_area_m2_type median_hole_area_m2;





  typedef boost::shared_ptr< ::corrosion_detector::NetStats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::corrosion_detector::NetStats_<ContainerAllocator> const> ConstPtr;

}; // struct NetStats_

typedef ::corrosion_detector::NetStats_<std::allocator<void> > NetStats;

typedef boost::shared_ptr< ::corrosion_detector::NetStats > NetStatsPtr;
typedef boost::shared_ptr< ::corrosion_detector::NetStats const> NetStatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::corrosion_detector::NetStats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::corrosion_detector::NetStats_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::corrosion_detector::NetStats_<ContainerAllocator1> & lhs, const ::corrosion_detector::NetStats_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.scale_m_per_px == rhs.scale_m_per_px &&
    lhs.median_hole_area_px == rhs.median_hole_area_px &&
    lhs.median_hole_area_m2 == rhs.median_hole_area_m2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::corrosion_detector::NetStats_<ContainerAllocator1> & lhs, const ::corrosion_detector::NetStats_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace corrosion_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::NetStats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::corrosion_detector::NetStats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::NetStats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corrosion_detector::NetStats_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::NetStats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corrosion_detector::NetStats_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::corrosion_detector::NetStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0b14b7f5d4cea4e0f0d1ef78c891d2e";
  }

  static const char* value(const ::corrosion_detector::NetStats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0b14b7f5d4cea4eULL;
  static const uint64_t static_value2 = 0x0f0d1ef78c891d2eULL;
};

template<class ContainerAllocator>
struct DataType< ::corrosion_detector::NetStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "corrosion_detector/NetStats";
  }

  static const char* value(const ::corrosion_detector::NetStats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::corrosion_detector::NetStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Escala calculada (metros/pixel)\n"
"float32 scale_m_per_px\n"
"\n"
"# Área mediana de los hexágonos (en píxeles cuadrados)\n"
"float32 median_hole_area_px\n"
"\n"
"# (Opcional) Área mediana en metros cuadrados (por si la quiere directa)\n"
"float32 median_hole_area_m2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::corrosion_detector::NetStats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::corrosion_detector::NetStats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.scale_m_per_px);
      stream.next(m.median_hole_area_px);
      stream.next(m.median_hole_area_m2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NetStats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::corrosion_detector::NetStats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::corrosion_detector::NetStats_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "scale_m_per_px: ";
    Printer<float>::stream(s, indent + "  ", v.scale_m_per_px);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "median_hole_area_px: ";
    Printer<float>::stream(s, indent + "  ", v.median_hole_area_px);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "median_hole_area_m2: ";
    Printer<float>::stream(s, indent + "  ", v.median_hole_area_m2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORROSION_DETECTOR_MESSAGE_NETSTATS_H
