// Generated by gencpp from file corrosion_detector/Trigger.msg
// DO NOT EDIT!


#ifndef CORROSION_DETECTOR_MESSAGE_TRIGGER_H
#define CORROSION_DETECTOR_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <corrosion_detector/TriggerRequest.h>
#include <corrosion_detector/TriggerResponse.h>


namespace corrosion_detector
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace corrosion_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::corrosion_detector::Trigger > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::corrosion_detector::Trigger&) { return value(); }
};

template<>
struct DataType< ::corrosion_detector::Trigger > {
  static const char* value()
  {
    return "corrosion_detector/Trigger";
  }

  static const char* value(const ::corrosion_detector::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::corrosion_detector::TriggerRequest> should match
// service_traits::MD5Sum< ::corrosion_detector::Trigger >
template<>
struct MD5Sum< ::corrosion_detector::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::corrosion_detector::Trigger >::value();
  }
  static const char* value(const ::corrosion_detector::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::corrosion_detector::TriggerRequest> should match
// service_traits::DataType< ::corrosion_detector::Trigger >
template<>
struct DataType< ::corrosion_detector::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::corrosion_detector::Trigger >::value();
  }
  static const char* value(const ::corrosion_detector::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::corrosion_detector::TriggerResponse> should match
// service_traits::MD5Sum< ::corrosion_detector::Trigger >
template<>
struct MD5Sum< ::corrosion_detector::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::corrosion_detector::Trigger >::value();
  }
  static const char* value(const ::corrosion_detector::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::corrosion_detector::TriggerResponse> should match
// service_traits::DataType< ::corrosion_detector::Trigger >
template<>
struct DataType< ::corrosion_detector::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::corrosion_detector::Trigger >::value();
  }
  static const char* value(const ::corrosion_detector::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORROSION_DETECTOR_MESSAGE_TRIGGER_H
