// Generated by gencpp from file cola2_msgs/DecimalLatLon.msg
// DO NOT EDIT!


#ifndef COLA2_MSGS_MESSAGE_DECIMALLATLON_H
#define COLA2_MSGS_MESSAGE_DECIMALLATLON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cola2_msgs
{
template <class ContainerAllocator>
struct DecimalLatLon_
{
  typedef DecimalLatLon_<ContainerAllocator> Type;

  DecimalLatLon_()
    : latitude(0.0)
    , longitude(0.0)  {
    }
  DecimalLatLon_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;





  typedef boost::shared_ptr< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> const> ConstPtr;

}; // struct DecimalLatLon_

typedef ::cola2_msgs::DecimalLatLon_<std::allocator<void> > DecimalLatLon;

typedef boost::shared_ptr< ::cola2_msgs::DecimalLatLon > DecimalLatLonPtr;
typedef boost::shared_ptr< ::cola2_msgs::DecimalLatLon const> DecimalLatLonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cola2_msgs::DecimalLatLon_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cola2_msgs::DecimalLatLon_<ContainerAllocator1> & lhs, const ::cola2_msgs::DecimalLatLon_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cola2_msgs::DecimalLatLon_<ContainerAllocator1> & lhs, const ::cola2_msgs::DecimalLatLon_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cola2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "680c6dc7da65a2421a822205dcbdb600";
  }

  static const char* value(const ::cola2_msgs::DecimalLatLon_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x680c6dc7da65a242ULL;
  static const uint64_t static_value2 = 0x1a822205dcbdb600ULL;
};

template<class ContainerAllocator>
struct DataType< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cola2_msgs/DecimalLatLon";
  }

  static const char* value(const ::cola2_msgs::DecimalLatLon_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Latitude and longitude, in decimal form.\n"
"\n"
"float64 latitude\n"
"float64 longitude\n"
"\n"
;
  }

  static const char* value(const ::cola2_msgs::DecimalLatLon_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DecimalLatLon_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cola2_msgs::DecimalLatLon_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cola2_msgs::DecimalLatLon_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLA2_MSGS_MESSAGE_DECIMALLATLON_H
