// Generated by gencpp from file cola2_msgs/Goto.msg
// DO NOT EDIT!


#ifndef COLA2_MSGS_MESSAGE_GOTO_H
#define COLA2_MSGS_MESSAGE_GOTO_H

#include <ros/service_traits.h>


#include <cola2_msgs/GotoRequest.h>
#include <cola2_msgs/GotoResponse.h>


namespace cola2_msgs
{

struct Goto
{

typedef GotoRequest Request;
typedef GotoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Goto
} // namespace cola2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cola2_msgs::Goto > {
  static const char* value()
  {
    return "d7ca42db7492724e2ad137e654c018a7";
  }

  static const char* value(const ::cola2_msgs::Goto&) { return value(); }
};

template<>
struct DataType< ::cola2_msgs::Goto > {
  static const char* value()
  {
    return "cola2_msgs/Goto";
  }

  static const char* value(const ::cola2_msgs::Goto&) { return value(); }
};


// service_traits::MD5Sum< ::cola2_msgs::GotoRequest> should match
// service_traits::MD5Sum< ::cola2_msgs::Goto >
template<>
struct MD5Sum< ::cola2_msgs::GotoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cola2_msgs::Goto >::value();
  }
  static const char* value(const ::cola2_msgs::GotoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cola2_msgs::GotoRequest> should match
// service_traits::DataType< ::cola2_msgs::Goto >
template<>
struct DataType< ::cola2_msgs::GotoRequest>
{
  static const char* value()
  {
    return DataType< ::cola2_msgs::Goto >::value();
  }
  static const char* value(const ::cola2_msgs::GotoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cola2_msgs::GotoResponse> should match
// service_traits::MD5Sum< ::cola2_msgs::Goto >
template<>
struct MD5Sum< ::cola2_msgs::GotoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cola2_msgs::Goto >::value();
  }
  static const char* value(const ::cola2_msgs::GotoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cola2_msgs::GotoResponse> should match
// service_traits::DataType< ::cola2_msgs::Goto >
template<>
struct DataType< ::cola2_msgs::GotoResponse>
{
  static const char* value()
  {
    return DataType< ::cola2_msgs::Goto >::value();
  }
  static const char* value(const ::cola2_msgs::GotoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLA2_MSGS_MESSAGE_GOTO_H
