// Generated by gencpp from file cola2_msgs/MaxJoyVelocity.msg
// DO NOT EDIT!


#ifndef COLA2_MSGS_MESSAGE_MAXJOYVELOCITY_H
#define COLA2_MSGS_MESSAGE_MAXJOYVELOCITY_H

#include <ros/service_traits.h>


#include <cola2_msgs/MaxJoyVelocityRequest.h>
#include <cola2_msgs/MaxJoyVelocityResponse.h>


namespace cola2_msgs
{

struct MaxJoyVelocity
{

typedef MaxJoyVelocityRequest Request;
typedef MaxJoyVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MaxJoyVelocity
} // namespace cola2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cola2_msgs::MaxJoyVelocity > {
  static const char* value()
  {
    return "65b63e684f31e94916e054c6a4a1b57f";
  }

  static const char* value(const ::cola2_msgs::MaxJoyVelocity&) { return value(); }
};

template<>
struct DataType< ::cola2_msgs::MaxJoyVelocity > {
  static const char* value()
  {
    return "cola2_msgs/MaxJoyVelocity";
  }

  static const char* value(const ::cola2_msgs::MaxJoyVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::cola2_msgs::MaxJoyVelocityRequest> should match
// service_traits::MD5Sum< ::cola2_msgs::MaxJoyVelocity >
template<>
struct MD5Sum< ::cola2_msgs::MaxJoyVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cola2_msgs::MaxJoyVelocity >::value();
  }
  static const char* value(const ::cola2_msgs::MaxJoyVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cola2_msgs::MaxJoyVelocityRequest> should match
// service_traits::DataType< ::cola2_msgs::MaxJoyVelocity >
template<>
struct DataType< ::cola2_msgs::MaxJoyVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::cola2_msgs::MaxJoyVelocity >::value();
  }
  static const char* value(const ::cola2_msgs::MaxJoyVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cola2_msgs::MaxJoyVelocityResponse> should match
// service_traits::MD5Sum< ::cola2_msgs::MaxJoyVelocity >
template<>
struct MD5Sum< ::cola2_msgs::MaxJoyVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cola2_msgs::MaxJoyVelocity >::value();
  }
  static const char* value(const ::cola2_msgs::MaxJoyVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cola2_msgs::MaxJoyVelocityResponse> should match
// service_traits::DataType< ::cola2_msgs::MaxJoyVelocity >
template<>
struct DataType< ::cola2_msgs::MaxJoyVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::cola2_msgs::MaxJoyVelocity >::value();
  }
  static const char* value(const ::cola2_msgs::MaxJoyVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLA2_MSGS_MESSAGE_MAXJOYVELOCITY_H
