// Generated by gencpp from file cola2_msgs/Mission.msg
// DO NOT EDIT!


#ifndef COLA2_MSGS_MESSAGE_MISSION_H
#define COLA2_MSGS_MESSAGE_MISSION_H

#include <ros/service_traits.h>


#include <cola2_msgs/MissionRequest.h>
#include <cola2_msgs/MissionResponse.h>


namespace cola2_msgs
{

struct Mission
{

typedef MissionRequest Request;
typedef MissionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Mission
} // namespace cola2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cola2_msgs::Mission > {
  static const char* value()
  {
    return "4c0bb5660c3e04aa8fcef310293495f7";
  }

  static const char* value(const ::cola2_msgs::Mission&) { return value(); }
};

template<>
struct DataType< ::cola2_msgs::Mission > {
  static const char* value()
  {
    return "cola2_msgs/Mission";
  }

  static const char* value(const ::cola2_msgs::Mission&) { return value(); }
};


// service_traits::MD5Sum< ::cola2_msgs::MissionRequest> should match
// service_traits::MD5Sum< ::cola2_msgs::Mission >
template<>
struct MD5Sum< ::cola2_msgs::MissionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cola2_msgs::Mission >::value();
  }
  static const char* value(const ::cola2_msgs::MissionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cola2_msgs::MissionRequest> should match
// service_traits::DataType< ::cola2_msgs::Mission >
template<>
struct DataType< ::cola2_msgs::MissionRequest>
{
  static const char* value()
  {
    return DataType< ::cola2_msgs::Mission >::value();
  }
  static const char* value(const ::cola2_msgs::MissionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cola2_msgs::MissionResponse> should match
// service_traits::MD5Sum< ::cola2_msgs::Mission >
template<>
struct MD5Sum< ::cola2_msgs::MissionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cola2_msgs::Mission >::value();
  }
  static const char* value(const ::cola2_msgs::MissionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cola2_msgs::MissionResponse> should match
// service_traits::DataType< ::cola2_msgs::Mission >
template<>
struct DataType< ::cola2_msgs::MissionResponse>
{
  static const char* value()
  {
    return DataType< ::cola2_msgs::Mission >::value();
  }
  static const char* value(const ::cola2_msgs::MissionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLA2_MSGS_MESSAGE_MISSION_H
