// Generated by gencpp from file cola2_msgs/PilotActionGoal.msg
// DO NOT EDIT!


#ifndef COLA2_MSGS_MESSAGE_PILOTACTIONGOAL_H
#define COLA2_MSGS_MESSAGE_PILOTACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <cola2_msgs/PilotGoal.h>

namespace cola2_msgs
{
template <class ContainerAllocator>
struct PilotActionGoal_
{
  typedef PilotActionGoal_<ContainerAllocator> Type;

  PilotActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  PilotActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::cola2_msgs::PilotGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PilotActionGoal_

typedef ::cola2_msgs::PilotActionGoal_<std::allocator<void> > PilotActionGoal;

typedef boost::shared_ptr< ::cola2_msgs::PilotActionGoal > PilotActionGoalPtr;
typedef boost::shared_ptr< ::cola2_msgs::PilotActionGoal const> PilotActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cola2_msgs::PilotActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cola2_msgs::PilotActionGoal_<ContainerAllocator1> & lhs, const ::cola2_msgs::PilotActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cola2_msgs::PilotActionGoal_<ContainerAllocator1> & lhs, const ::cola2_msgs::PilotActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cola2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a90334a1a2d706b7114c459a016d976";
  }

  static const char* value(const ::cola2_msgs::PilotActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a90334a1a2d706bULL;
  static const uint64_t static_value2 = 0x7114c459a016d976ULL;
};

template<class ContainerAllocator>
struct DataType< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cola2_msgs/PilotActionGoal";
  }

  static const char* value(const ::cola2_msgs::PilotActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"PilotGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cola2_msgs/PilotGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the REQUEST\n"
"\n"
"# Initial state\n"
"float64 initial_latitude\n"
"float64 initial_longitude\n"
"float64 initial_depth\n"
"\n"
"# Final state\n"
"float64 final_latitude\n"
"float64 final_longitude\n"
"float64 final_depth\n"
"float64 final_yaw\n"
"float64 final_altitude\n"
"\n"
"# Heave mode\n"
"uint64 heave_mode\n"
"uint64 DEPTH=0\n"
"uint64 ALTITUDE=1\n"
"uint64 BOTH=2\n"
"\n"
"# Surge velocity\n"
"float64 surge_velocity\n"
"\n"
"# Tolerance\n"
"float64 tolerance_xy\n"
"\n"
"# Timeout\n"
"float64 timeout\n"
"\n"
"# Controller type\n"
"uint64 controller_type\n"
"uint64 SECTION=0\n"
"uint64 ANCHOR=1\n"
"uint64 HOLONOMIC_KEEP_POSITION=2\n"
"uint8 SWAY_SECTION = 3\n"
"\n"
"# Requester and priority\n"
"cola2_msgs/GoalDescriptor goal\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cola2_msgs/GoalDescriptor\n"
"# Contains values common to all waypoint request and status messages.\n"
"# Waypoint goals with higher priority trump lower priority goals. For\n"
"# goals of the same priority, the pilot should follow the latest\n"
"# received.\n"
"\n"
"# Name of the requesting node, used with id to identify the request.\n"
"string requester\n"
"\n"
"uint32 priority\n"
"\n"
"# PRIORITY DEFINITIONS\n"
"uint32 PRIORITY_TELEOPERATION_LOW = 0\n"
"uint32 PRIORITY_SAFETY_LOW = 5\n"
"uint32 PRIORITY_NORMAL = 10\n"
"uint32 PRIORITY_SAFETY = 30\n"
"uint32 PRIORITY_TELEOPERATION = 40\n"
"uint32 PRIORITY_SAFETY_HIGH  = 50\n"
"uint32 PRIORITY_TELEOPERATION_HIGH = 60\n"
;
  }

  static const char* value(const ::cola2_msgs::PilotActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PilotActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cola2_msgs::PilotActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cola2_msgs::PilotActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::cola2_msgs::PilotGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLA2_MSGS_MESSAGE_PILOTACTIONGOAL_H
