// Generated by gencpp from file cola2_msgs/Setpoints.msg
// DO NOT EDIT!


#ifndef COLA2_MSGS_MESSAGE_SETPOINTS_H
#define COLA2_MSGS_MESSAGE_SETPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cola2_msgs
{
template <class ContainerAllocator>
struct Setpoints_
{
  typedef Setpoints_<ContainerAllocator> Type;

  Setpoints_()
    : header()
    , setpoints()  {
    }
  Setpoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , setpoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _setpoints_type;
  _setpoints_type setpoints;





  typedef boost::shared_ptr< ::cola2_msgs::Setpoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cola2_msgs::Setpoints_<ContainerAllocator> const> ConstPtr;

}; // struct Setpoints_

typedef ::cola2_msgs::Setpoints_<std::allocator<void> > Setpoints;

typedef boost::shared_ptr< ::cola2_msgs::Setpoints > SetpointsPtr;
typedef boost::shared_ptr< ::cola2_msgs::Setpoints const> SetpointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cola2_msgs::Setpoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cola2_msgs::Setpoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cola2_msgs::Setpoints_<ContainerAllocator1> & lhs, const ::cola2_msgs::Setpoints_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.setpoints == rhs.setpoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cola2_msgs::Setpoints_<ContainerAllocator1> & lhs, const ::cola2_msgs::Setpoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cola2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cola2_msgs::Setpoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cola2_msgs::Setpoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cola2_msgs::Setpoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cola2_msgs::Setpoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cola2_msgs::Setpoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cola2_msgs::Setpoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cola2_msgs::Setpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d13a8e7b230df87e00dd540874a14b59";
  }

  static const char* value(const ::cola2_msgs::Setpoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd13a8e7b230df87eULL;
  static const uint64_t static_value2 = 0x00dd540874a14b59ULL;
};

template<class ContainerAllocator>
struct DataType< ::cola2_msgs::Setpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cola2_msgs/Setpoints";
  }

  static const char* value(const ::cola2_msgs::Setpoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cola2_msgs::Setpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] setpoints\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cola2_msgs::Setpoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cola2_msgs::Setpoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.setpoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Setpoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cola2_msgs::Setpoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cola2_msgs::Setpoints_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "setpoints: ";
    if (v.setpoints.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.setpoints.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.setpoints[i]);
    }
    if (v.setpoints.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLA2_MSGS_MESSAGE_SETPOINTS_H
