# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from corrosion_detector/AxisPoints.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class AxisPoints(genpy.Message):
  _md5sum = "c40b075900f16fe11733d8a1bb7afb1b"
  _type = "corrosion_detector/AxisPoints"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

# List of 2D points
geometry_msgs/Point major_axis_p1
geometry_msgs/Point major_axis_p2
geometry_msgs/Point minor_axis_p1
geometry_msgs/Point minor_axis_p2

# Orientation of the axis (yaw in radians)
float64 orientation

# Axis lenghts
float64 major_axis_len
float64 minor_axis_len

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','major_axis_p1','major_axis_p2','minor_axis_p1','minor_axis_p2','orientation','major_axis_len','minor_axis_len']
  _slot_types = ['std_msgs/Header','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,major_axis_p1,major_axis_p2,minor_axis_p1,minor_axis_p2,orientation,major_axis_len,minor_axis_len

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AxisPoints, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.major_axis_p1 is None:
        self.major_axis_p1 = geometry_msgs.msg.Point()
      if self.major_axis_p2 is None:
        self.major_axis_p2 = geometry_msgs.msg.Point()
      if self.minor_axis_p1 is None:
        self.minor_axis_p1 = geometry_msgs.msg.Point()
      if self.minor_axis_p2 is None:
        self.minor_axis_p2 = geometry_msgs.msg.Point()
      if self.orientation is None:
        self.orientation = 0.
      if self.major_axis_len is None:
        self.major_axis_len = 0.
      if self.minor_axis_len is None:
        self.minor_axis_len = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.major_axis_p1 = geometry_msgs.msg.Point()
      self.major_axis_p2 = geometry_msgs.msg.Point()
      self.minor_axis_p1 = geometry_msgs.msg.Point()
      self.minor_axis_p2 = geometry_msgs.msg.Point()
      self.orientation = 0.
      self.major_axis_len = 0.
      self.minor_axis_len = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15d().pack(_x.major_axis_p1.x, _x.major_axis_p1.y, _x.major_axis_p1.z, _x.major_axis_p2.x, _x.major_axis_p2.y, _x.major_axis_p2.z, _x.minor_axis_p1.x, _x.minor_axis_p1.y, _x.minor_axis_p1.z, _x.minor_axis_p2.x, _x.minor_axis_p2.y, _x.minor_axis_p2.z, _x.orientation, _x.major_axis_len, _x.minor_axis_len))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.major_axis_p1 is None:
        self.major_axis_p1 = geometry_msgs.msg.Point()
      if self.major_axis_p2 is None:
        self.major_axis_p2 = geometry_msgs.msg.Point()
      if self.minor_axis_p1 is None:
        self.minor_axis_p1 = geometry_msgs.msg.Point()
      if self.minor_axis_p2 is None:
        self.minor_axis_p2 = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 120
      (_x.major_axis_p1.x, _x.major_axis_p1.y, _x.major_axis_p1.z, _x.major_axis_p2.x, _x.major_axis_p2.y, _x.major_axis_p2.z, _x.minor_axis_p1.x, _x.minor_axis_p1.y, _x.minor_axis_p1.z, _x.minor_axis_p2.x, _x.minor_axis_p2.y, _x.minor_axis_p2.z, _x.orientation, _x.major_axis_len, _x.minor_axis_len,) = _get_struct_15d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15d().pack(_x.major_axis_p1.x, _x.major_axis_p1.y, _x.major_axis_p1.z, _x.major_axis_p2.x, _x.major_axis_p2.y, _x.major_axis_p2.z, _x.minor_axis_p1.x, _x.minor_axis_p1.y, _x.minor_axis_p1.z, _x.minor_axis_p2.x, _x.minor_axis_p2.y, _x.minor_axis_p2.z, _x.orientation, _x.major_axis_len, _x.minor_axis_len))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.major_axis_p1 is None:
        self.major_axis_p1 = geometry_msgs.msg.Point()
      if self.major_axis_p2 is None:
        self.major_axis_p2 = geometry_msgs.msg.Point()
      if self.minor_axis_p1 is None:
        self.minor_axis_p1 = geometry_msgs.msg.Point()
      if self.minor_axis_p2 is None:
        self.minor_axis_p2 = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 120
      (_x.major_axis_p1.x, _x.major_axis_p1.y, _x.major_axis_p1.z, _x.major_axis_p2.x, _x.major_axis_p2.y, _x.major_axis_p2.z, _x.minor_axis_p1.x, _x.minor_axis_p1.y, _x.minor_axis_p1.z, _x.minor_axis_p2.x, _x.minor_axis_p2.y, _x.minor_axis_p2.z, _x.orientation, _x.major_axis_len, _x.minor_axis_len,) = _get_struct_15d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_15d = None
def _get_struct_15d():
    global _struct_15d
    if _struct_15d is None:
        _struct_15d = struct.Struct("<15d")
    return _struct_15d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
