// Auto-generated. Do not edit!

// (in-package cola2_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let PilotActionGoal = require('./PilotActionGoal.js');
let PilotActionResult = require('./PilotActionResult.js');
let PilotActionFeedback = require('./PilotActionFeedback.js');

//-----------------------------------------------------------

class PilotAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new PilotActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new PilotActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new PilotActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PilotAction
    // Serialize message field [action_goal]
    bufferOffset = PilotActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = PilotActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = PilotActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PilotAction
    let len;
    let data = new PilotAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = PilotActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = PilotActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = PilotActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += PilotActionGoal.getMessageSize(object.action_goal);
    length += PilotActionResult.getMessageSize(object.action_result);
    length += PilotActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'cola2_msgs/PilotAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '21c402743baa5d01391db54431926544';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    PilotActionGoal action_goal
    PilotActionResult action_result
    PilotActionFeedback action_feedback
    
    ================================================================================
    MSG: cola2_msgs/PilotActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    PilotGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: cola2_msgs/PilotGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the REQUEST
    
    # Initial state
    float64 initial_latitude
    float64 initial_longitude
    float64 initial_depth
    
    # Final state
    float64 final_latitude
    float64 final_longitude
    float64 final_depth
    float64 final_yaw
    float64 final_altitude
    
    # Heave mode
    uint64 heave_mode
    uint64 DEPTH=0
    uint64 ALTITUDE=1
    uint64 BOTH=2
    
    # Surge velocity
    float64 surge_velocity
    
    # Tolerance
    float64 tolerance_xy
    
    # Timeout
    float64 timeout
    
    # Controller type
    uint64 controller_type
    uint64 SECTION=0
    uint64 ANCHOR=1
    uint64 HOLONOMIC_KEEP_POSITION=2
    uint8 SWAY_SECTION = 3
    
    # Requester and priority
    cola2_msgs/GoalDescriptor goal
    
    
    ================================================================================
    MSG: cola2_msgs/GoalDescriptor
    # Contains values common to all waypoint request and status messages.
    # Waypoint goals with higher priority trump lower priority goals. For
    # goals of the same priority, the pilot should follow the latest
    # received.
    
    # Name of the requesting node, used with id to identify the request.
    string requester
    
    uint32 priority
    
    # PRIORITY DEFINITIONS
    uint32 PRIORITY_TELEOPERATION_LOW = 0
    uint32 PRIORITY_SAFETY_LOW = 5
    uint32 PRIORITY_NORMAL = 10
    uint32 PRIORITY_SAFETY = 30
    uint32 PRIORITY_TELEOPERATION = 40
    uint32 PRIORITY_SAFETY_HIGH  = 50
    uint32 PRIORITY_TELEOPERATION_HIGH = 60
    
    ================================================================================
    MSG: cola2_msgs/PilotActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    PilotResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: cola2_msgs/PilotResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the RESULT
    
    # State
    uint64 state
    uint64 SUCCESS=0
    uint64 TIMEOUT=1
    uint64 FAILURE=2
    
    
    ================================================================================
    MSG: cola2_msgs/PilotActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    PilotFeedback feedback
    
    ================================================================================
    MSG: cola2_msgs/PilotFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a FEEDBACK
    
    # Errors
    float64 distance_to_end
    float64 cross_track_error
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PilotAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = PilotActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new PilotActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = PilotActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new PilotActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = PilotActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new PilotActionFeedback()
    }

    return resolved;
    }
};

module.exports = PilotAction;
