// Auto-generated. Do not edit!

// (in-package cola2_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PilotFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.distance_to_end = null;
      this.cross_track_error = null;
    }
    else {
      if (initObj.hasOwnProperty('distance_to_end')) {
        this.distance_to_end = initObj.distance_to_end
      }
      else {
        this.distance_to_end = 0.0;
      }
      if (initObj.hasOwnProperty('cross_track_error')) {
        this.cross_track_error = initObj.cross_track_error
      }
      else {
        this.cross_track_error = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PilotFeedback
    // Serialize message field [distance_to_end]
    bufferOffset = _serializer.float64(obj.distance_to_end, buffer, bufferOffset);
    // Serialize message field [cross_track_error]
    bufferOffset = _serializer.float64(obj.cross_track_error, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PilotFeedback
    let len;
    let data = new PilotFeedback(null);
    // Deserialize message field [distance_to_end]
    data.distance_to_end = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [cross_track_error]
    data.cross_track_error = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'cola2_msgs/PilotFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd59c9d2fe125e9dbd3a7afe6b7739fc4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a FEEDBACK
    
    # Errors
    float64 distance_to_end
    float64 cross_track_error
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PilotFeedback(null);
    if (msg.distance_to_end !== undefined) {
      resolved.distance_to_end = msg.distance_to_end;
    }
    else {
      resolved.distance_to_end = 0.0
    }

    if (msg.cross_track_error !== undefined) {
      resolved.cross_track_error = msg.cross_track_error;
    }
    else {
      resolved.cross_track_error = 0.0
    }

    return resolved;
    }
};

module.exports = PilotFeedback;
