(cl:in-package cola2_msgs-msg)
(cl:export '(INITIAL_LATITUDE-VAL
          INITIAL_LATITUDE
          INITIAL_LONGITUDE-VAL
          INITIAL_LONGITUDE
          INITIAL_DEPTH-VAL
          INITIAL_DEPTH
          FINAL_LATITUDE-VAL
          FINAL_LATITUDE
          FINAL_LONGITUDE-VAL
          FINAL_LONGITUDE
          FINAL_DEPTH-VAL
          FINAL_DEPTH
          FINAL_YAW-VAL
          FINAL_YAW
          FINAL_ALTITUDE-VAL
          FINAL_ALTITUDE
          HEAVE_MODE-VAL
          HEAVE_MODE
          SURGE_VELOCITY-VAL
          SURGE_VELOCITY
          TOLERANCE_XY-VAL
          TOLERANCE_XY
          TIMEOUT-VAL
          TIMEOUT
          CONTROLLER_TYPE-VAL
          CONTROLLER_TYPE
          GOAL-VAL
          GOAL
))