; Auto-generated. Do not edit!


(cl:in-package cola2_msgs-msg)


;//! \htmlinclude PilotResult.msg.html

(cl:defclass <PilotResult> (roslisp-msg-protocol:ros-message)
  ((state
    :reader state
    :initarg :state
    :type cl:integer
    :initform 0))
)

(cl:defclass PilotResult (<PilotResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PilotResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PilotResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cola2_msgs-msg:<PilotResult> is deprecated: use cola2_msgs-msg:PilotResult instead.")))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <PilotResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cola2_msgs-msg:state-val is deprecated.  Use cola2_msgs-msg:state instead.")
  (state m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<PilotResult>)))
    "Constants for message type '<PilotResult>"
  '((:SUCCESS . 0)
    (:TIMEOUT . 1)
    (:FAILURE . 2))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'PilotResult)))
    "Constants for message type 'PilotResult"
  '((:SUCCESS . 0)
    (:TIMEOUT . 1)
    (:FAILURE . 2))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PilotResult>) ostream)
  "Serializes a message object of type '<PilotResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'state)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PilotResult>) istream)
  "Deserializes a message object of type '<PilotResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'state)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PilotResult>)))
  "Returns string type for a message object of type '<PilotResult>"
  "cola2_msgs/PilotResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PilotResult)))
  "Returns string type for a message object of type 'PilotResult"
  "cola2_msgs/PilotResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PilotResult>)))
  "Returns md5sum for a message object of type '<PilotResult>"
  "27ba8f4a492a7897c4adf64391e75b6a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PilotResult)))
  "Returns md5sum for a message object of type 'PilotResult"
  "27ba8f4a492a7897c4adf64391e75b6a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PilotResult>)))
  "Returns full string definition for message of type '<PilotResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the RESULT~%~%# State~%uint64 state~%uint64 SUCCESS=0~%uint64 TIMEOUT=1~%uint64 FAILURE=2~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PilotResult)))
  "Returns full string definition for message of type 'PilotResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the RESULT~%~%# State~%uint64 state~%uint64 SUCCESS=0~%uint64 TIMEOUT=1~%uint64 FAILURE=2~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PilotResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PilotResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PilotResult
    (cl:cons ':state (state msg))
))
